/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppActionsRouteImport } from './routes/_app/actions'
import { Route as AppReadinessIndexRouteImport } from './routes/_app/readiness/index'
import { Route as AppEvidenceIndexRouteImport } from './routes/_app/evidence/index'
import { Route as AppEvidenceEvidenceIdRouteImport } from './routes/_app/evidence/$evidenceId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessIndexRoute = AppReadinessIndexRouteImport.update({
  id: '/readiness/',
  path: '/readiness/',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceIndexRoute = AppEvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceEvidenceIdRoute = AppEvidenceEvidenceIdRouteImport.update({
  id: '/evidence/$evidenceId',
  path: '/evidence/$evidenceId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof AppActionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/evidence': typeof AppEvidenceIndexRoute
  '/readiness': typeof AppReadinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof AppActionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/evidence': typeof AppEvidenceIndexRoute
  '/readiness': typeof AppReadinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/actions': typeof AppActionsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/_app/evidence/': typeof AppEvidenceIndexRoute
  '/_app/readiness/': typeof AppReadinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/dashboard'
    | '/evidence/$evidenceId'
    | '/evidence'
    | '/readiness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/dashboard'
    | '/evidence/$evidenceId'
    | '/evidence'
    | '/readiness'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/actions'
    | '/_app/dashboard'
    | '/_app/evidence/$evidenceId'
    | '/_app/evidence/'
    | '/_app/readiness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actions': {
      id: '/_app/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/readiness/': {
      id: '/_app/readiness/'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof AppReadinessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence/': {
      id: '/_app/evidence/'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AppEvidenceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence/$evidenceId': {
      id: '/_app/evidence/$evidenceId'
      path: '/evidence/$evidenceId'
      fullPath: '/evidence/$evidenceId'
      preLoaderRoute: typeof AppEvidenceEvidenceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEvidenceEvidenceIdRoute: typeof AppEvidenceEvidenceIdRoute
  AppEvidenceIndexRoute: typeof AppEvidenceIndexRoute
  AppReadinessIndexRoute: typeof AppReadinessIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEvidenceEvidenceIdRoute: AppEvidenceEvidenceIdRoute,
  AppEvidenceIndexRoute: AppEvidenceIndexRoute,
  AppReadinessIndexRoute: AppReadinessIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
