/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSignOffRouteImport } from './routes/_app/sign-off'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPresentationRouteImport } from './routes/_app/presentation'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppChecklistRouteImport } from './routes/_app/checklist'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppEvidenceEvidenceIdRouteImport } from './routes/_app/evidence/$evidenceId'
import { Route as AppDashboardQsIndexRouteImport } from './routes/_app/dashboard/qs/index'
import { Route as AppDashboardQsQsIdRouteImport } from './routes/_app/dashboard/qs/$qsId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSignOffRoute = AppSignOffRouteImport.update({
  id: '/sign-off',
  path: '/sign-off',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPresentationRoute = AppPresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistRoute = AppChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceEvidenceIdRoute = AppEvidenceEvidenceIdRouteImport.update({
  id: '/evidence/$evidenceId',
  path: '/evidence/$evidenceId',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardQsIndexRoute = AppDashboardQsIndexRouteImport.update({
  id: '/dashboard/qs/',
  path: '/dashboard/qs/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardQsQsIdRoute = AppDashboardQsQsIdRouteImport.update({
  id: '/dashboard/qs/$qsId',
  path: '/dashboard/qs/$qsId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/checklist': typeof AppChecklistRoute
  '/documents': typeof AppDocumentsRoute
  '/presentation': typeof AppPresentationRoute
  '/settings': typeof AppSettingsRoute
  '/sign-off': typeof AppSignOffRoute
  '/team': typeof AppTeamRoute
  '/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/qs/$qsId': typeof AppDashboardQsQsIdRoute
  '/dashboard/qs': typeof AppDashboardQsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/checklist': typeof AppChecklistRoute
  '/documents': typeof AppDocumentsRoute
  '/presentation': typeof AppPresentationRoute
  '/settings': typeof AppSettingsRoute
  '/sign-off': typeof AppSignOffRoute
  '/team': typeof AppTeamRoute
  '/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/qs/$qsId': typeof AppDashboardQsQsIdRoute
  '/dashboard/qs': typeof AppDashboardQsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/checklist': typeof AppChecklistRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/presentation': typeof AppPresentationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sign-off': typeof AppSignOffRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/qs/$qsId': typeof AppDashboardQsQsIdRoute
  '/_app/dashboard/qs/': typeof AppDashboardQsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/checklist'
    | '/documents'
    | '/presentation'
    | '/settings'
    | '/sign-off'
    | '/team'
    | '/evidence/$evidenceId'
    | '/dashboard'
    | '/dashboard/qs/$qsId'
    | '/dashboard/qs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/checklist'
    | '/documents'
    | '/presentation'
    | '/settings'
    | '/sign-off'
    | '/team'
    | '/evidence/$evidenceId'
    | '/dashboard'
    | '/dashboard/qs/$qsId'
    | '/dashboard/qs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/checklist'
    | '/_app/documents'
    | '/_app/presentation'
    | '/_app/settings'
    | '/_app/sign-off'
    | '/_app/team'
    | '/_app/evidence/$evidenceId'
    | '/_app/dashboard/'
    | '/_app/dashboard/qs/$qsId'
    | '/_app/dashboard/qs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-off': {
      id: '/_app/sign-off'
      path: '/sign-off'
      fullPath: '/sign-off'
      preLoaderRoute: typeof AppSignOffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presentation': {
      id: '/_app/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof AppPresentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklist': {
      id: '/_app/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AppChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence/$evidenceId': {
      id: '/_app/evidence/$evidenceId'
      path: '/evidence/$evidenceId'
      fullPath: '/evidence/$evidenceId'
      preLoaderRoute: typeof AppEvidenceEvidenceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/qs/': {
      id: '/_app/dashboard/qs/'
      path: '/dashboard/qs'
      fullPath: '/dashboard/qs'
      preLoaderRoute: typeof AppDashboardQsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/qs/$qsId': {
      id: '/_app/dashboard/qs/$qsId'
      path: '/dashboard/qs/$qsId'
      fullPath: '/dashboard/qs/$qsId'
      preLoaderRoute: typeof AppDashboardQsQsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChecklistRoute: typeof AppChecklistRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppPresentationRoute: typeof AppPresentationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignOffRoute: typeof AppSignOffRoute
  AppTeamRoute: typeof AppTeamRoute
  AppEvidenceEvidenceIdRoute: typeof AppEvidenceEvidenceIdRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardQsQsIdRoute: typeof AppDashboardQsQsIdRoute
  AppDashboardQsIndexRoute: typeof AppDashboardQsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChecklistRoute: AppChecklistRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppPresentationRoute: AppPresentationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignOffRoute: AppSignOffRoute,
  AppTeamRoute: AppTeamRoute,
  AppEvidenceEvidenceIdRoute: AppEvidenceEvidenceIdRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardQsQsIdRoute: AppDashboardQsQsIdRoute,
  AppDashboardQsIndexRoute: AppDashboardQsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
